import * as T from 'three';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
import {GLTFLoader} from 'three/addons/loaders/GLTFLoader.js';
import {EffectComposer} from 'three/addons/postprocessing/EffectComposer.js';
import {RenderPass} from 'three/addons/postprocessing/RenderPass.js';
import {SSAOPass} from 'three/addons/postprocessing/SSAOPass.js';
import {SMAAPass} from 'three/addons/postprocessing/SMAAPass.js';
import {OutputPass} from 'three/addons/postprocessing/OutputPass.js';
const params=new URLSearchParams(location.search);if(params.has('capture'))document.body.classList.add('capture');
const version=params.get('version')==='v1'?'v1':'v2';const assetRoot='/assets/3d/'+version+'/';
const view=document.querySelector('#viewport'),status=document.querySelector('#status');
const renderer=new T.WebGLRenderer({antialias:true,preserveDrawingBuffer:true});renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));renderer.shadowMap.enabled=true;renderer.shadowMap.type=T.VSMShadowMap;renderer.toneMapping=T.ACESFilmicToneMapping;renderer.toneMappingExposure=1.04;view.prepend(renderer.domElement);
const scene=new T.Scene();scene.background=new T.Color('#f0ede6');const camera=new T.OrthographicCamera(-9,9,8,-8,.1,100);camera.position.set(13,12,16);
const controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=true;controls.dampingFactor=.065;controls.minPolarAngle=.28;controls.maxPolarAngle=Math.PI/2.12;controls.minZoom=.55;controls.maxZoom=3.5;controls.autoRotateSpeed=.45;
scene.add(new T.HemisphereLight('#fff4e4','#a9a397',1.65));const sun=new T.DirectionalLight('#fff0d9',2.75);sun.position.set(-4,10,3);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);Object.assign(sun.shadow.camera,{left:-10,right:10,top:10,bottom:-10,near:1,far:35});sun.shadow.normalBias=.018;sun.shadow.bias=-.0003;sun.shadow.radius=4;sun.shadow.blurSamples=8;scene.add(sun);const fill=new T.DirectionalLight('#e3ecf7',.85);fill.position.set(4,7,-5);scene.add(fill);
const ground=new T.Mesh(new T.PlaneGeometry(200,200),new T.MeshStandardMaterial({color:'#f0ede6',roughness:1}));ground.rotation.x=-Math.PI/2;ground.position.y=-.34;ground.receiveShadow=true;scene.add(ground);
const composer=new EffectComposer(renderer);composer.addPass(new RenderPass(scene,camera));const ao=new SSAOPass(scene,camera,view.clientWidth,view.clientHeight);ao.kernelRadius=.28;ao.minDistance=.003;ao.maxDistance=.20;composer.addPass(ao);composer.addPass(new SMAAPass());composer.addPass(new OutputPass());
ao.ssaoMaterial.defines.PERSPECTIVE_CAMERA=0;ao.ssaoMaterial.needsUpdate=true;
const names={studio:'完整工作室',room:'房间',desk:'标准工位',chair:'办公椅',employee:'基础员工',plant:'绿植',bookshelf:'书架',console:'总控台',sofa:'沙发',...(version==='v2'?{coffeeTable:'茶几'}:{})};
document.querySelector('.edition').textContent='ASSET STUDY / '+(version==='v2'?'02':'01');
if(version==='v1')document.querySelector('.note').textContent='第一版造型与动作资产，保留用于对比。';
const manifest=await fetch(assetRoot+'manifest.json').then(r=>r.json());const loader=new GLTFLoader();let model,mixer,current='studio',motion='Working',paused=false,showLabels=true,loadId=0,labels=[],actions=[];
for(const key of Object.keys(names)){const b=document.createElement('button');b.textContent=names[key];b.dataset.asset=key;b.onclick=()=>load(key);document.querySelector('#assets').append(b);}
function disposeModel(root){const gs=new Set(),ms=new Set(),ts=new Set();root.traverse(o=>{if(o.isMesh){gs.add(o.geometry);for(const m of Array.isArray(o.material)?o.material:[o.material]){ms.add(m);for(const v of Object.values(m))if(v?.isTexture)ts.add(v);}}});gs.forEach(x=>x.dispose());ms.forEach(x=>x.dispose());ts.forEach(x=>x.dispose());}
function frame(){const box=new T.Box3().setFromObject(model),center=box.getCenter(new T.Vector3()),size=box.getSize(new T.Vector3());const r=Math.max(size.x*.60,size.z*.65,size.y*.9,.8);controls.target.copy(center);camera.position.copy(center).add(new T.Vector3(version==='v2'?-.92:1.1,.91,1.5).multiplyScalar(r*1.6));camera.zoom=1;camera.userData.span=current==='studio'||current==='room'?11.8:r*1.6;controls.minDistance=r*.7;controls.maxDistance=r*5;ground.position.y=box.min.y-.02;resize();controls.update();}
function play(){if(!mixer)return;for(const a of actions)a.fadeOut(.25);actions=[];for(const clip of model.animations){if(clip.name===motion||clip.name.startsWith(motion+'_')){const a=mixer.clipAction(clip);a.reset().fadeIn(.25).play();actions.push(a);}}document.querySelectorAll('[data-motion]').forEach(b=>b.classList.toggle('selected',b.dataset.motion===motion));updateLabelText();}
function updateLabelText(){for(const item of labels){const idle=motion==='Idle';item.el.classList.toggle('idle',idle);item.el.innerHTML=`<i></i>${item.name} · ${motion==='Working'?'工作中':motion==='Error'?'检查异常':'待命'}`;}}
async function load(key){const id=++loadId;window.previewReady=false;status.hidden=false;status.textContent='正在载入 3D 资产…';try{const gltf=await loader.loadAsync(assetRoot+key+'.glb');if(id!==loadId){disposeModel(gltf.scene);return;}if(model){mixer?.stopAllAction();mixer?.uncacheRoot(model);scene.remove(model);disposeModel(model);}current=key;model=gltf.scene;model.animations=gltf.animations;model.traverse(o=>{if(o.isMesh){o.castShadow=o.material.name!=='window';o.receiveShadow=true;for(const m of Array.isArray(o.material)?o.material:[o.material])if(m.map)m.map.anisotropy=Math.min(8,renderer.capabilities.getMaxAnisotropy());}});scene.add(model);mixer=new T.AnimationMixer(model);actions=[];document.querySelector('#labels').replaceChildren();labels=[];
  if(key==='studio'){let data;model.traverse(o=>{if(o.userData.labels)data=o.userData.labels;});for(const item of data||[]){const el=document.createElement('div');el.className='label';document.querySelector('#labels').append(el);labels.push({...item,el});}}
  play();frame();document.querySelectorAll('[data-asset]').forEach(b=>b.classList.toggle('selected',b.dataset.asset===key));document.querySelector('#scene-name').textContent=key==='studio'?'一个安静运转的小团队':names[key];const info=manifest.assets.find(x=>x.name===key);document.querySelector('#stats').innerHTML=`${info.triangles.toLocaleString()} 三角面 · ${info.meshes} 网格<br>${(info.bytes/1024/1024).toFixed(2)} MB · GLB · Y 轴向上`;const a=document.querySelector('#download');a.href=assetRoot+key+'.glb';status.hidden=true;window.previewReady=true;window.previewInfo={key,version,animations:gltf.animations.length,...info};}catch(e){status.textContent='载入失败：'+e.message;console.error(e);}}
function resize(){const w=view.clientWidth,h=view.clientHeight;renderer.setSize(w,h);const span=camera.userData.span||12.3;camera.left=-span*w/h/2;camera.right=span*w/h/2;camera.top=span/2;camera.bottom=-span/2;camera.updateProjectionMatrix();composer.setSize(w,h);}
new ResizeObserver(resize).observe(view);document.querySelector('#reset').onclick=frame;document.querySelector('#rotate').onclick=e=>{controls.autoRotate=!controls.autoRotate;e.target.classList.toggle('selected',controls.autoRotate);};document.querySelector('#pause').onclick=e=>{paused=!paused;e.target.textContent=paused?'继续动画':'暂停动画';};document.querySelector('#labels-toggle').onclick=e=>{showLabels=!showLabels;e.target.textContent=showLabels?'隐藏标签':'显示标签';};for(const b of document.querySelectorAll('[data-motion]'))b.onclick=()=>{motion=b.dataset.motion;play();};
let last=performance.now();function tick(now){requestAnimationFrame(tick);const dt=Math.min((now-last)/1000,.05);last=now;if(document.hidden)return;controls.update();if(!paused)mixer?.update(dt);ao.ssaoMaterial.uniforms.cameraProjectionMatrix.value.copy(camera.projectionMatrix);ao.ssaoMaterial.uniforms.cameraInverseProjectionMatrix.value.copy(camera.projectionMatrixInverse);for(const item of labels){const p=new T.Vector3(...item.anchor).project(camera);item.el.style.left=(p.x*.5+.5)*view.clientWidth+'px';item.el.style.top=(-p.y*.5+.5)*view.clientHeight+'px';item.el.hidden=!showLabels||current!=='studio'||p.z>1;}composer.render();}requestAnimationFrame(tick);
window.studioPreview={load,frame,get model(){return model;},get renderer(){return renderer;},get mixer(){return mixer;},get camera(){return camera;},get controls(){return controls;}};
await load(params.get('asset')||'studio');
